"""Add embedding column to DocumentChunk model

Revision ID: 4275b4c7310f
Revises: 5bdccb13acda
Create Date: 2026-08-24 11:32:27.542799

"""

from collections.abc import Sequence

import pgvector
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4275b4c7310f"
down_revision: str | Sequence[str] | None = "5bdccb13acda"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document_chunks",
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("document_chunks", "embedding")
    # ### end Alembic commands ###
