"""Create DocumentFile table

Revision ID: 44018df326e0
Revises: e62bea3b5af3
Create Date: 2026-08-02 23:25:04.873850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '44018df326e0'
down_revision: Union[str, Sequence[str], None] = 'e62bea3b5af3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', postgresql.ENUM('LOCAL', 'S3', name='storage_provider'), nullable=False),
    sa.Column('bucket', sa.String(length=255), nullable=True),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_files')),
    sa.UniqueConstraint('provider', 'bucket', 'storage_key', name=op.f('uq_document_files_provider'))
    )
    op.create_index('ix_document_file_checksum', 'document_files', ['checksum'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_document_file_checksum', table_name='document_files')
    op.drop_table('document_files')
    # ### end Alembic commands ###
