"""Add rewritten_query column; Update created_at default to clock_timestamp() to reflect insertion time

Revision ID: 5c2c162b424f
Revises: b8d426f8f9b3
Create Date: 2026-09-23 00:18:21.730838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c2c162b424f'
down_revision: Union[str, Sequence[str], None] = 'b8d426f8f9b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_messages', sa.Column('rewritten_query', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation_messages', 'rewritten_query')
    # ### end Alembic commands ###
